# Generated by Django 5.0.3 on 2024-04-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='last_ran_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
