# Generated by Django 5.0.4 on 2024-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_rules_last_ran_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ran_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rules',
            name='balance',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='rules',
            name='initial_investment',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='rules',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
