# Generated by Django 5.0.4 on 2024-04-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_rulejobs_rules_balance_rules_initial_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
