# Generated by Django 5.2.2 on 2025-06-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_rules_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RuleJobs',
        ),
    ]
