# Generated by Django 5.0.2 on 2024-03-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=75)),
                ('exchange_name', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=10)),
                ('stock_type', models.CharField(max_length=12)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'name'], name='stocks_stoc_ticker_7e2ecb_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_phrase', models.CharField(max_length=75)),
                ('search_args', models.CharField(max_length=512, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['search_phrase'], name='stocks_stoc_search__d18376_idx'), models.Index(fields=['search_args'], name='stocks_stoc_search__719824_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('high', models.FloatField(default=0.0, max_length=28)),
                ('low', models.FloatField(default=0.0, max_length=28)),
                ('open', models.FloatField(default=0.0, max_length=28)),
                ('close', models.FloatField(default=0.0, max_length=28)),
                ('granularity', models.CharField(max_length=4)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stocks')),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'timestamp', 'granularity'], name='stocks_stoc_ticker__f939d5_idx')],
            },
        ),
    ]
