# Generated by Django 5.0.2 on 2024-02-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=75)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
