# Generated by Django 5.0.2 on 2024-03-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stocksearch',
            name='stocks_stoc_search__7cc4ff_idx',
        ),
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='ticker',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='search_args',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='stocksearch',
            name='search_phrase',
            field=models.CharField(max_length=75),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['ticker', 'timestamp', 'granularity'], name='stocks_stoc_ticker__f939d5_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksearch',
            index=models.Index(fields=['search_phrase'], name='stocks_stoc_search__d18376_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksearch',
            index=models.Index(fields=['search_args'], name='stocks_stoc_search__719824_idx'),
        ),
    ]
