# Generated by Django 5.0.2 on 2024-02-25 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='stocks',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='stocks',
            index=models.Index(fields=['ticker', 'name'], name='stocks_stoc_ticker_7e2ecb_idx'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stocks'),
        ),
    ]
