# Generated by Django 5.0.2 on 2024-02-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockdata_stocks_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
