# Generated by Django 5.0.4 on 2024-04-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stocks_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='exchange_close',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='exchange_gmtoffset',
            field=models.IntegerField(default=-14400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='exchange_open',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
