# Generated by Django 5.0.4 on 2024-04-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stockdata_exchange_gmtoffset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='exchange_gmtoffset',
            field=models.IntegerField(default=-14400),
        ),
    ]
