# Generated by Django 5.0.4 on 2024-04-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_stockdata_timestamp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stocksearch',
            name='stocks_stoc_search__d18376_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocksearch',
            name='stocks_stoc_search__719824_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('ticker', 'timestamp', 'granularity')},
        ),
        migrations.AlterUniqueTogether(
            name='stocks',
            unique_together={('ticker', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stocksearch',
            unique_together={('search_phrase', 'search_args')},
        ),
        migrations.AddIndex(
            model_name='stocksearch',
            index=models.Index(fields=['search_phrase', 'search_args'], name='stocks_stoc_search__7cc4ff_idx'),
        ),
    ]
