# Generated by Django 5.0.4 on 2024-04-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_remove_stockdata_stocks_stoc_ticker__f939d5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='day_close',
            field=models.FloatField(default=0.0, max_length=28),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='day_open',
            field=models.FloatField(default=0.0, max_length=28),
        ),
    ]
