# Generated by Django 5.0.4 on 2024-04-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stockdata_day_close_stockdata_day_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='day_close',
            field=models.FloatField(blank=True, max_length=28, null=True),
        ),
    ]
