# Generated by Django 5.0.3 on 2024-04-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0004_alter_users_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
