# Generated by Django 5.0.4 on 2024-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='balance',
            field=models.FloatField(default=0.0, max_length=28),
        ),
        migrations.AddField(
            model_name='transactions',
            name='current_profit_loss',
            field=models.FloatField(default=0.0, max_length=28),
        ),
        migrations.AddField(
            model_name='transactions',
            name='initial_investment',
            field=models.FloatField(default=0.0, max_length=28),
        ),
        migrations.AddField(
            model_name='transactions',
            name='total_shares',
            field=models.IntegerField(default=0),
        ),
    ]
