# Generated by Django 5.2.2 on 2025-06-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='start_date',
        ),
    ]
