FROM node:lts-bookworm AS development

ENV CI=true
ENV PORT=80

WORKDIR /react-app
COPY reactjs/package.json .

RUN npm install \
    && npm install -g serve

RUN cp package*.json /

CMD [ "bash", "-c", "npm start && sleep inf" ]