FROM node:lts-bookworm AS development

ENV CI=true
ENV PORT=80

WORKDIR /react-app
COPY reactjs/package.json .

RUN npm set progress=false \
    && npm install

RUN cp package*.json /
RUN apt-get update \
    && apt-get install vim -y

COPY reactjs/index.html .
COPY reactjs/jest.config.js .
COPY reactjs/tsconfig.js .
COPY reactjs/tsconfig.node.js .
COPY reactjs/vite.config.js .

CMD [ "bash", "-c", "npm run dev && sleep inf" ]
#CMD [ "bash", "-c", "sleep inf" ]