FROM node:lts-bookworm AS builder

ENV CI=true
ENV PORT=80

WORKDIR /react-app
COPY reactjs/package*.json .

RUN npm ci

COPY reactjs/. .

RUN npm run build

FROM nginx:bookworm

RUN mkdir -p /etc/nginx/sites-enabled

COPY ./BuildTools/nginx/* /etc/nginx/

COPY --from=builder /react-app/dist /usr/share/nginx/html